# Generated by Django 3.1.3 on 2022-01-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='아이디')),
                ('name', models.CharField(max_length=32, verbose_name='이름')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('phone_num', models.CharField(max_length=32, unique=True, verbose_name='휴대전화')),
                ('company_name', models.CharField(max_length=32, verbose_name='회사명')),
                ('company_address', models.CharField(max_length=64, verbose_name='회사 주소')),
                ('company_tel', models.CharField(max_length=128, verbose_name='회사 전화')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='이메일')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='계정 생성시간')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'user',
            },
        ),
    ]
