# Generated by Django 3.1.3 on 2022-01-18 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220118_1011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
