# Generated by Django 3.1.3 on 2022-02-10 01:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_index', models.AutoField(primary_key=True, serialize=False, verbose_name='카테고리 인덱스')),
                ('category_main', models.CharField(max_length=50, verbose_name='메인 카테고리')),
                ('category_sub', models.CharField(max_length=50, verbose_name='서브 카테고리')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('board_index', models.AutoField(primary_key=True, serialize=False, verbose_name='게시글 인덱스')),
                ('rating', models.FloatField(verbose_name='별점')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='작성일')),
                ('content', models.CharField(max_length=500, verbose_name='내용')),
                ('review_img', models.CharField(max_length=100, verbose_name='이미지 주소')),
                ('category_index', models.ForeignKey(db_column='category_index', on_delete=django.db.models.deletion.CASCADE, related_name='review_category_index', to='itrencotech.category', verbose_name='카테고리 인덱스')),
                ('userid', models.ForeignKey(db_column='userid', default='deleted_user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='review_userid', to=settings.AUTH_USER_MODEL, verbose_name='작성자 아이디')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('board_index', models.AutoField(primary_key=True, serialize=False, verbose_name='게시글 인덱스')),
                ('portfolio_img', models.CharField(max_length=100, verbose_name='이미지 주소')),
                ('content', models.CharField(max_length=500, verbose_name='내용')),
                ('category_index', models.ForeignKey(db_column='category_index', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_category_index', to='itrencotech.category', verbose_name='카테고리 인덱스')),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_num', models.AutoField(primary_key=True, serialize=False, verbose_name='주문 번호')),
                ('company_name', models.CharField(max_length=30, verbose_name='회사명')),
                ('business_num', models.CharField(max_length=255, verbose_name='사업자 등록 번호')),
                ('name', models.CharField(max_length=50, verbose_name='담당자')),
                ('email', models.CharField(max_length=100, verbose_name='이메일')),
                ('phone_num', models.CharField(max_length=13, verbose_name='연락처')),
                ('title', models.CharField(max_length=100, verbose_name='제품 제목')),
                ('description', models.CharField(max_length=255, verbose_name='제품 설명')),
                ('material', models.CharField(max_length=100, verbose_name='소재')),
                ('quantity', models.IntegerField(default=1, verbose_name='제품 수량')),
                ('size', models.CharField(max_length=255, verbose_name='크기(가로/세로/높이)')),
                ('path', models.CharField(max_length=255, verbose_name='파일 경로')),
                ('etc', models.CharField(max_length=255, null=True, verbose_name='기타')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='주문일')),
                ('state', models.CharField(default='Got it', max_length=20, verbose_name='주문 상태')),
                ('category_index', models.ForeignKey(db_column='category_index', default='deleted_category', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order_category_index', to='itrencotech.category', verbose_name='카테고리 인덱스')),
                ('userid', models.ForeignKey(db_column='userid', default='deleted_user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order_userid', to=settings.AUTH_USER_MODEL, verbose_name='주문자 아이디')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
