# Generated by Django 3.1.3 on 2022-01-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('category_index', models.AutoField(primary_key=True, serialize=False, verbose_name='카테고리 인덱스')),
                ('category_main', models.CharField(max_length=50, verbose_name='메인 카테고리')),
                ('category_sub', models.CharField(max_length=50, verbose_name='서브 카테고리')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
