# Generated by Django 3.1.3 on 2022-02-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itrencotech', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
