# Generated by Django 3.1.3 on 2022-01-20 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itrencotech', '0002_portfoliomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_index',
            field=models.ForeignKey(db_column='카테고리 인덱스', on_delete=django.db.models.deletion.CASCADE, related_name='portfoliomodel_category_index', to='itrencotech.categorymodel', verbose_name='카테고리 인덱스'),
        ),
    ]
