# Generated by Django 3.1.3 on 2022-01-20 05:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('itrencotech', '0003_auto_20220120_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('board_index', models.AutoField(primary_key=True, serialize=False, verbose_name='게시글 인덱스')),
                ('rating', models.FloatField(verbose_name='별점')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='작성일')),
                ('content', models.CharField(max_length=500, verbose_name='내용')),
                ('review_img', models.CharField(max_length=100, verbose_name='이미지 주소')),
                ('category_index', models.ForeignKey(db_column='카테고리 인덱스', on_delete=django.db.models.deletion.CASCADE, related_name='reviewmodel_category_index', to='itrencotech.categorymodel', verbose_name='카테고리 인덱스')),
                ('user_id', models.ForeignKey(db_column='작성자 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='reviewmodel_user_id', to='common.usermodel', verbose_name='작성자 아이디')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
